In [2]:
import pandas as pd

In [17]:
for sheet_name, df in sheet.items():
    print(f"Sheet Name: {sheet_name}")
    print(df)  # 输出对应的 DataFrame
    print("\n")

Sheet Name: Sheet
Empty DataFrame
Columns: []
Index: []


Sheet Name: 实验日期_2023-08-19 20-07-42
                               time  byte1  byte2  byte3 byte4 byte5 byte6  \
model
model1:Voltage  2023-08-19 20:14:43      0      0      0    C7    FF    FF
model1:Voltage  2023-08-19 20:16:04      0      0      0    C6    FF    FF
model1:Voltage  2023-08-19 20:16:04      0      0      0    C7    FF    FF
model1:Voltage  2023-08-19 20:16:05      0      0      0    C6    FF    FF
model1:Voltage  2023-08-19 20:16:06      0      0      0    C5    FF    FF
...                             ...    ...    ...    ...   ...   ...   ...
model3:Loading  2023-08-19 20:16:53      0      0      2    00    26    FF
model3:Loading  2023-08-19 20:16:53      0      0      2    00    1B    FF
model3:Loading  2023-08-19 20:16:53      0      0      2    00    1C    FF
model3:Loading  2023-08-19 20:16:54      0      0      2    00    38    FF
model3:Loading  2023-08-19 20:17:04      0      0      2    00    1A    FF

               byte7 byte8  byte1.1  byte2.1  byte3.1  byte4.1  byte5.1  \
model
model1:Voltage    FF    CE        0        0        0      199      255
model1:Voltage    FF    CB        0        0        0      198      255
model1:Voltage    FF    CF        0        0        0      199      255
model1:Voltage    FF    CD        0        0        0      198      255
model1:Voltage    FF    D0        0        0        0      197      255
...              ...   ...      ...      ...      ...      ...      ...
model3:Loading    FF    C7        0        0        2        0       38
model3:Loading    FF    CA        0        0        2        0       27
model3:Loading    FF    CB        0        0        2        0       28
model3:Loading    FF    CB        0        0        2        0       56
model3:Loading    FF    CD        0        0        2        0       26

                byte6.1  byte7.1  byte8.1     data1  data2
model
model1:Voltage      255      255      206  2985.000    NaN
model1:Voltage      255      255      203  2970.000    NaN
model1:Voltage      255      255      207  2985.000    NaN
model1:Voltage      255      255      205  2970.000    NaN
model1:Voltage      255      255      208  2955.000    NaN
...                 ...      ...      ...       ...    ...
model3:Loading      255      255      199    57.988    NaN
model3:Loading      255      255      202    41.202    NaN
model3:Loading      255      255      203    42.728    NaN
model3:Loading      255      255      203    85.456    NaN
model3:Loading      255      255      205    39.676    NaN

[62 rows x 19 columns]


Sheet Name: 实验日期_2023-08-19 20-32-03
                               time  byte1  byte2  byte3 byte4 byte5 byte6  \
model
model1:Voltage  2023-08-19 20:32:44      0      0      0    C7    FF    FF
model1:Voltage  2023-08-19 20:33:40      0      0      0    C6    FF    FF
model2:P&T      2023-08-19 20:32:45      0      0      1    2A    56    FF
model2:P&T      2023-08-19 20:34:05      0      0      1    2A    56    FF
model3:Loading  2023-08-19 20:32:51      0      0      2    00    25    FF
model3:Loading  2023-08-19 20:33:25      0      0      2    00    38    FF
model3:Loading  2023-08-19 20:33:40      0      0      2    00    19    FF
model3:Loading  2023-08-19 20:33:45      0      0      2    00    26    FF
model3:Loading  2023-08-19 20:33:47      0      0      2    00    25    FF

               byte7 byte8  byte1.1  byte2.1  byte3.1  byte4.1  byte5.1  \
model
model1:Voltage    FF    C3        0        0        0      199      255
model1:Voltage    FF    C4        0        0        0      198      255
model2:P&T        FF    CB        0        0        1       42       86
model2:P&T        FF    C0        0        0        1       42       86
model3:Loading    FF    C8        0        0        2        0       37
model3:Loading    FF    C2        0        0        2        0       56
model3:Loading    FF    C8        0        0        2        0       25
model3:Loading    FF    CA        0        0        2        0       38
model3:Loading    FF    CA        0        0        2        0       37

                byte6.1  byte7.1  byte8.1     data1  data2
model
model1:Voltage      255      255      195  2985.000    NaN
model1:Voltage      255      255      196  2970.000    NaN
model2:P&T          255      255      203   230.580   36.0
model2:P&T          255      255      192   230.580   36.0
model3:Loading      255      255      200    56.462    NaN
model3:Loading      255      255      194    85.456    NaN
model3:Loading      255      255      200    38.150    NaN
model3:Loading      255      255      202    57.988    NaN
model3:Loading      255      255      202    56.462    NaN


Sheet Name: 实验日期_2023-08-19 20-34-26
                               time  byte1  byte2  byte3 byte4 byte5 byte6  \
model
model1:Voltage  2023-08-19 20:35:20      0      0      0    C5    FF    FF
model1:Voltage  2023-08-19 20:35:25      0      0      0    C5    FF    FF
model1:Voltage  2023-08-19 20:35:27      0      0      0    C5    FF    FF
model2:P&T      2023-08-19 20:35:18      0      0      1    2A    56    FF
model2:P&T      2023-08-19 20:35:20      0      0      1    2A    56    FF
model2:P&T      2023-08-19 20:35:27      0      0      1    2A    56    FF
model2:P&T      2023-08-19 20:36:15      0      0      1    2A    56    FF
model3:Loading  2023-08-19 20:35:18      0      0      2    00    19    FF
model3:Loading  2023-08-19 20:35:20      0      0      2    00    1F    FF
model3:Loading  2023-08-19 20:35:23      0      0      2    00    1F    FF
model3:Loading  2023-08-19 20:35:25      0      0      2    00    21    FF
model3:Loading  2023-08-19 20:35:27      0      0      2    00    31    FF

               byte7 byte8  byte1.1  byte2.1  byte3.1  byte4.1  byte5.1  \
model
model1:Voltage    FF    B9        0        0        0      197      255
model1:Voltage    FF    B2        0        0        0      197      255
model1:Voltage    FF    BC        0        0        0      197      255
model2:P&T        FF    C9        0        0        1       42       86
model2:P&T        FF    C9        0        0        1       42       86
model2:P&T        FF    C9        0        0        1       42       86
model2:P&T        FF    C1        0        0        1       42       86
model3:Loading    FF    C9        0        0        2        0       25
model3:Loading    FF    C8        0        0        2        0       31
model3:Loading    FF    C8        0        0        2        0       31
model3:Loading    FF    C8        0        0        2        0       33
model3:Loading    FF    CA        0        0        2        0       49

                byte6.1  byte7.1  byte8.1     data1  data2
model
model1:Voltage      255      255      185  2955.000    NaN
model1:Voltage      255      255      178  2955.000    NaN
model1:Voltage      255      255      188  2955.000    NaN
model2:P&T          255      255      201   230.580   36.0
model2:P&T          255      255      201   230.580   36.0
model2:P&T          255      255      201   230.580   36.0
model2:P&T          255      255      193   230.580   36.0
model3:Loading      255      255      201    38.150    NaN
model3:Loading      255      255      200    47.306    NaN
model3:Loading      255      255      200    47.306    NaN
model3:Loading      255      255      200    50.358    NaN
model3:Loading      255      255      202    74.774    NaN

In [16]:
test1=sheet["实验日期_2023-08-19 20-32-03"]#字典类型的索引
type(test1)
test1

,time,byte1,byte2,byte3,byte4,byte5,byte6,byte7,byte8,byte1.1,byte2.1,byte3.1,byte4.1,byte5.1,byte6.1,byte7.1,byte8.1,data1,data2
model,,,,,,,,,,,,,,,,,,,
model1:Voltage,2023-08-19 20:32:44,0,0,0,C7,FF,FF,FF,C3,0,0,0,199,255,255,255,195,2985.000,NaN
model1:Voltage,2023-08-19 20:33:40,0,0,0,C6,FF,FF,FF,C4,0,0,0,198,255,255,255,196,2970.000,NaN
model2:P&T,2023-08-19 20:32:45,0,0,1,2A,56,FF,FF,CB,0,0,1,42,86,255,255,203,230.580,36.0
model2:P&T,2023-08-19 20:34:05,0,0,1,2A,56,FF,FF,C0,0,0,1,42,86,255,255,192,230.580,36.0
model3:Loading,2023-08-19 20:32:51,0,0,2,00,25,FF,FF,C8,0,0,2,0,37,255,255,200,56.462,NaN
model3:Loading,2023-08-19 20:33:25,0,0,2,00,38,FF,FF,C2,0,0,2,0,56,255,255,194,85.456,NaN
model3:Loading,2023-08-19 20:33:40,0,0,2,00,19,FF,FF,C8,0,0,2,0,25,255,255,200,38.150,NaN
model3:Loading,2023-08-19 20:33:45,0,0,2,00,26,FF,FF,CA,0,0,2,0,38,255,255,202,57.988,NaN
model3:Loading,2023-08-19 20:33:47,0,0,2,00,25,FF,FF,CA,0,0,2,0,37,255,255,202,56.462,NaN

In [4]:
test1=sheet[key:]#字典类型的索引
type(test1)
test1

,time,byte1,byte2,byte3,byte4,byte5,byte6,byte7,byte8,byte1.1,byte2.1,byte3.1,byte4.1,byte5.1,byte6.1,byte7.1,byte8.1,data1,data2
model,,,,,,,,,,,,,,,,,,,
model1:Voltage,2023-08-19 20:14:43,0,0,0,C7,FF,FF,FF,CE,0,0,0,199,255,255,255,206,2985.000,NaN
model1:Voltage,2023-08-19 20:16:04,0,0,0,C6,FF,FF,FF,CB,0,0,0,198,255,255,255,203,2970.000,NaN
model1:Voltage,2023-08-19 20:16:04,0,0,0,C7,FF,FF,FF,CF,0,0,0,199,255,255,255,207,2985.000,NaN
model1:Voltage,2023-08-19 20:16:05,0,0,0,C6,FF,FF,FF,CD,0,0,0,198,255,255,255,205,2970.000,NaN
model1:Voltage,2023-08-19 20:16:06,0,0,0,C5,FF,FF,FF,D0,0,0,0,197,255,255,255,208,2955.000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
model3:Loading,2023-08-19 20:16:53,0,0,2,00,26,FF,FF,C7,0,0,2,0,38,255,255,199,57.988,NaN
model3:Loading,2023-08-19 20:16:53,0,0,2,00,1B,FF,FF,CA,0,0,2,0,27,255,255,202,41.202,NaN
model3:Loading,2023-08-19 20:16:53,0,0,2,00,1C,FF,FF,CB,0,0,2,0,28,255,255,203,42.728,NaN
model3:Loading,2023-08-19 20:16:54,0,0,2,00,38,FF,FF,CB,0,0,2,0,56,255,255,203,85.456,NaN
model3:Loading,2023-08-19 20:17:04,0,0,2,00,1A,FF,FF,CD,0,0,2,0,26,255,255,205,39.676,NaN

In [5]:
#%%!做数据分析，要反应正常的情况，应该使用众数
#按照列进行索引
test1_data=test1.groupby("model")["data1"].agg(list)#分组依据，变为list,从新定义缩影标签
test1_data
# type(test1_data)
# test1_data=pd.Series(test1_data,index=["model1","model2","model3"])
# test_moderesult=test1_data[].mode()#求众数
# print(test_moderesult)

model
model1:Voltage    [2985.0, 2970.0, 2985.0, 2970.0, 2955.0, 2970....
model2:P&T        [230.58, 230.58, 230.58, 230.58, 230.58, 230.5...
model3:Loading    [53.41, 77.826, 53.41, 73.248, 53.41, 48.832, ...
Name: data1, dtype: object

In [6]:
test1_data1=pd.Series(test1_data[0],name="model1:Voltage").mode()
test1_data1

0    2970.0
Name: model1:Voltage, dtype: float64

In [7]:
test1_data2=pd.Series(test1_data[1],name="model2:P&T").mode()
test1_data2

0    230.58
Name: model2:P&T, dtype: float64

In [11]:
test1_data3=pd.Series(test1_data[2],name="model3:Loading").mode()

test1_data3

0    53.410
1    71.722
Name: model3:Loading, dtype: float64

In [13]:
count=pd.Series(test1_data[2]).value_counts()
count
count1=count[53.410]#如何去除报错
count1
# count

4